# -*- coding: utf-8 -*-
"""SVM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19u6T0vmmkVDnvY3KYDapIDr85LgRDN2s
"""

# !pip install tslearn
# !pip install scikit-learn

import csv
from sklearn import svm
import numpy as np
import joblib

X = []
y = []

maxm = 3000

with open('output.csv', 'r') as file:
    reader = csv.reader(file)
    for row in reader:
        y.append(int(row[-1]))
        if(len(row)>maxm):
          row = row[:maxm+1]
        temp = []
        for val in row[:-2]:
          temp.append(float(val))
        X.append(temp)

for x in X:
  for i in range(maxm-len(x)):
    x.append(0.0)

clf = svm.SVC(C=10, kernel="rbf")
clf.fit(X,y)
joblib.dump(clf, 'trained_model.pkl')

X = []
y = []

maxm = 3000

with open('test.csv', 'r') as file:
    reader = csv.reader(file)
    for row in reader:
        y.append(int(row[-1]))
        if(len(row)>maxm):
          row = row[:maxm+1]
        temp = []
        for val in row[:-2]:
          temp.append(float(val))
        X.append(temp)

for x in X:
  for i in range(maxm-len(x)):
    x.append(0.0)
    
loaded_model = joblib.load('trained_model.pkl')
result = loaded_model.score(X, y)
print("Score :",result)